### ISSUE TITLE
Dates before unix epoch not considered valid

### ISSUE THREAD

**Issue by abakst** [kristapsdz/openradtool#13]
Thank you very much for providing these (kcgi, openradtool, etc) tools! I've noticed that the valid-checks generated by `ort-source` seem to mark unix times from before 1970 as invalid (as they are non-negative). I'm not sure what the implications of doing so are, but deleting the `case`s for `FTYPE_DATE` and `FTYPE_EPOCH` in the function linked below ought to fix this.

https://github.com/kristapsdz/openradtool/blob/ede695b8eabd4ad4e7193e00bb215b26297992a1/csource.c#L1771

**Comment by kristapsdz** [comment]
That won't do anything: it's where the "limit" statements would be applied, e.g., `field ctime epoch limit ge 0`.  Which version of kcgi are you using?  Recent versions (0.12 and above) have spent a lot of time on making sure the time and date functions work properly.

**Comment by abakst** [comment]
Eek sorry! I just noticed that the data model includes `gt 0`, so it looks like it's behaving as expected! I'll close the issue now, thanks!
